# Generated by Django 4.1.2 on 2022-12-08 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AboutApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Login',
            new_name='About',
        ),
    ]
