# Generated by Django 4.1.2 on 2022-12-08 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AboutApp', '0003_about_gender_about_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='Phone',
            field=models.CharField(max_length=2000),
        ),
    ]
