# Generated by Django 4.1.2 on 2022-12-24 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('WorkID', models.AutoField(primary_key=True, serialize=False)),
                ('ProfileID', models.IntegerField(blank=True)),
                ('ProfileName', models.CharField(max_length=100)),
                ('ProfilePicture', models.CharField(blank=True, max_length=2000)),
                ('ProfileRating', models.FloatField(blank=True)),
                ('WorkTittle', models.CharField(max_length=20000)),
                ('WorkPicture', models.CharField(max_length=2000)),
                ('WorkRating', models.FloatField(blank=True)),
                ('WorkReview', models.IntegerField(blank=True)),
                ('StartingMoney', models.IntegerField(blank=True)),
                ('WorkSummery', models.CharField(max_length=20000000000000)),
                ('WorkDetails', models.CharField(max_length=2000000000000000000000000)),
                ('WorkCatagory', models.CharField(max_length=20000)),
            ],
        ),
    ]
