# Generated by Django 4.1.2 on 2022-12-25 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='workSubCatagory',
            field=models.CharField(max_length=20000, null=True),
        ),
    ]
