# Generated by Django 4.1.2 on 2022-12-25 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkApp', '0002_work_worksubcatagory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catagory',
            fields=[
                ('CatID', models.IntegerField(primary_key=True, serialize=False)),
                ('catSub', models.CharField(max_length=20000000000000000000)),
            ],
        ),
    ]
