# Generated by Django 4.1.2 on 2022-12-09 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Active',
            fields=[
                ('ProfileID', models.IntegerField(primary_key=True, serialize=False)),
                ('ActiveTime', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('FollowID', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
