# Generated by Django 4.1.2 on 2022-10-28 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('ProfileID', models.IntegerField(primary_key=True, serialize=False)),
                ('ProfileName', models.CharField(max_length=2000)),
                ('ProfilePicture', models.CharField(blank=True, max_length=2000)),
                ('ProfileCoverPhoto', models.CharField(blank=True, max_length=2000)),
                ('ProfileBio', models.CharField(blank=True, max_length=2000)),
            ],
        ),
    ]
