# Generated by Django 4.1.2 on 2022-12-21 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('PostID', models.AutoField(primary_key=True, serialize=False)),
                ('ProfileID', models.IntegerField(blank=True)),
                ('ProfileName', models.CharField(max_length=100)),
                ('ProfilePicture', models.CharField(blank=True, max_length=2000)),
                ('PostDate', models.DateTimeField(auto_now_add=True)),
                ('PostImage', models.CharField(blank=True, max_length=2000)),
                ('PostMessage', models.CharField(blank=True, max_length=2000)),
                ('PostLikeCnt', models.IntegerField(blank=True)),
                ('PostLikeList', models.CharField(blank=True, max_length=2000)),
                ('PostCommentCnt', models.IntegerField(blank=True)),
                ('PostCommentList', models.CharField(blank=True, max_length=2000)),
                ('PostTag', models.CharField(blank=True, max_length=20000)),
            ],
        ),
    ]
