# Generated by Django 4.1.2 on 2022-10-28 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MessageApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='Message',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='message',
            name='MessageReceiverProfilePicture',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='message',
            name='MessageSenderProfilePicture',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
